### ISSUE TITLE
compatibility with PingIdentity client sdk

### ISSUE THREAD

**Issue by martinpritchard** [BetterCloud/scim2#2]
I am having some difficulty getting the /Schemas endpoint to work with the same objects that I use with the PingIdentity client sdk.

If I define a custom object, in order for it to be discoverable with the /Schemas endpoint it needs to extend `com.bettercloud.scim2.common.BaseScimResource`.  However, in order for it to be used with the client sdk, it needs to extend the unboundid package `com.unboundid.scim2.common.BaseScimResource`

I have a workaround, which is to define the class twice, extending from different packages, but this is not ideal

Also, could you shed some light on the reasoning for the branching of the ping identity sdk-common?  Was there some incompatibility?

**Comment by dantlynch** [comment]
sdk-common was branched to allow us to enhance the library as ping identity does not accept PRs from third parties.  For example the Schema annotation was updated to make allowing ignoring unrecognized properties during deserialization configurable. In addition, the ping identity sdk-common is not easy to extend with additional functionality. For example adding custom filter types is very difficult. We intend on eventually rewriting this library to make it easy to extend/override default implementations.

**Comment by dantlynch** [comment]
Closing this issue since compatibility with the PingIdentity client is not supported.
